### ISSUE TITLE
deleteById not works ??

### ISSUE THREAD

**Issue by mdelahiguera** [impesa/loopback-connector-gdatastore#1]
It seems deleteById doesn't work for my API when it connects with the gdatastore

**Comment by dfonsecam** [comment]
Thanks mdelahiguera. Which version of loopback do you have?

**Comment by mdelahiguera** [comment]
I have used 2.x and 3.x version, and it doesn't work. On the other hand, findById Method calls to GDataStore.prototype.all and it never calls to GDataStore.prototype.findById. Thanks in advance

**Comment by dfonsecam** [comment]
DeleteById for autogenerated datastore ids requires the following configuration in each model
"id": {
      "id": true,
      "type": "number"
}
The problem was generated because you tried to find a string id
