### ISSUE TITLE
Add support for gt, gte, lt & lte

### ISSUE THREAD

**Issue by glesage** [impesa/loopback-connector-gdatastore#3]
https://github.com/impesa/loopback-connector-gdatastore/pull/2

Let me know if you have any thoughts on this, seems to work pretty well.. just basic support for inequality checks (which seem to be handled fine on @google-cloud/datastore)

**Comment by dfonsecam** [comment]
Thanks Geoffroy, seems to work good! Now you can download the 1.0.6 package with your changes.

**Comment by glesage** [comment]
Great sounds good bud
